main: supreme.andrey.homes.SupremeHomes
name: 'SupremeHomes2'
version: '2.2.0'
api: '1.16'
api-version: '1.16'
description: A set homes plugin for your's servers, this plugin contain a public set homes too, very useful for player shops
author: Andrey H. (Supreme)
softdepend:
  - "Vault"

commands:
  sethome:
    description: set your home, usage /sethome <name of home>
    usage: /<command>
    permission: suphomes.sethome
  home:
    description: teleport you to you home, usage /home <name of home>
    usage: /<command>
    permission: suphomes.home
  homes:
    description: show all your homes, usage /home
    usage: /<command>
    permission: suphomes.homes
  delhome:
    description: delete a home, usage /delhome <homename>
    usage: /<command>
    permission: suphomes.delhome
  setpublic:
    description: set a home as public, other players can access
    usage: /<command>
    permission: suphomes.public.set
  unsetpublic:
    description: set a public home as private
    usage: /<command>
    permission: suphomes.public.unset
  show:
    description: show players home in a GUI
    usage: /<command>
    permission: suphomes.show
 # test:
  # usage: /<command>
    
permissions:
  suphomes.player:
   description: 'Allow the defaults home command to players (sethome home homes and delhome)'
   default: true
   children:
    suphomes.sethome: true
    suphomes.home: true
    suphomes.homes: true
    suphomes.delhome: true
  suphomes.public:
    description: 'Allow player to set your homes to public or private'
    default: true
    children:
     suphomes.public.set: true
     suphomes.public.unset: true
     
  suphomes.admin:
   description: 'Allow some admin tools for server admin'
   default: op
   children:
    suphomes.show: true
  
    
    
    